openapi: 3.1.0
info:
  title: Comment Module API
  version: 1.1.0
  description: >-
    Comment module APIs covering subject registration, threaded conversations, reactions, and moderation.
    Mutating operations accept optional `Idempotency-Key` headers and honor ETag/If-Match for optimistic concurrency.
  license:
    name: Proprietary
    url: https://mycorp.com/legal/terms
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
  - url: https://comments.mycorp.com/api/comments/v1
    description: Production
  - url: https://comments-staging.mycorp.com/api/comments/v1
    description: Staging
tags:
  - name: Subjects
    description: Subject discovery and policy management.
  - name: Comments
    description: Threaded comment authoring and retrieval.
  - name: Reactions
    description: Upvotes, downvotes, and emoji interactions.
  - name: Moderation
    description: Tools for reviewers and community safety.
  - name: Metrics
    description: Aggregated counters and analytic snapshots.
  - name: Events
    description: Server-sent events for near-real-time updates.
security:
  - bearerAuth: []
paths:
  /subjects/{subject_key}:
    $ref: './openapi/subjects.yaml#/paths/~1subjects~1{subject_key}'
  /subjects/by-key/{subject_key}:
    $ref: './openapi/subjects.yaml#/paths/~1subjects~1by-key~1{subject_key}'
  /subjects/id/{subject_id}:
    $ref: './openapi/subjects.yaml#/paths/~1subjects~1id~1{subject_id}'
  /subjects/id/{subject_id}/metrics:
    $ref: './openapi/subjects.yaml#/paths/~1subjects~1id~1{subject_id}~1metrics'
  /subjects/id/{subject_id}/comments:
    $ref: './openapi/comments.yaml#/paths/~1subjects~1id~1{subject_id}~1comments'
  /comments/{comment_id}:
    $ref: './openapi/comments.yaml#/paths/~1comments~1{comment_id}'
  /comments/{comment_id}/replies:
    $ref: './openapi/comments.yaml#/paths/~1comments~1{comment_id}~1replies'
  /comments/{comment_id}/reactions:
    $ref: './openapi/reactions.yaml#/paths/~1comments~1{comment_id}~1reactions'
  /comments/{comment_id}/reactions/{type}:
    $ref: './openapi/reactions.yaml#/paths/~1comments~1{comment_id}~1reactions~1{type}'
  /comments/{comment_id}/reports:
    $ref: './openapi/moderation.yaml#/paths/~1comments~1{comment_id}~1reports'
  /moderation/comments:
    $ref: './openapi/moderation.yaml#/paths/~1moderation~1comments'
  /moderation/comments/{comment_id}/actions:
    $ref: './openapi/moderation.yaml#/paths/~1moderation~1comments~1{comment_id}~1actions'
  /subjects/id/{subject_id}/events:
    $ref: './openapi/events.yaml#/paths/~1subjects~1id~1{subject_id}~1events'
components:
  $ref: './openapi/components.yaml#/components'
